fix: deploy cert

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -144,40 +144,40 @@ jobs:
       # PRISMA MIGRATION
       # ==========================================================
 
-      - name: Run Prisma migration
-        env:
-          IMAGE_TAG: ${{ steps.vars.outputs.tag }}
-        run: |
-          set -euo pipefail
+      # - name: Run Prisma migration
+      #   env:
+      #     IMAGE_TAG: ${{ steps.vars.outputs.tag }}
+      #   run: |
+      #     set -euo pipefail
 
-          echo "🔹 Running Prisma migration"
+      #     echo "🔹 Running Prisma migration"
 
-          kubectl delete job kikos-prisma-migrate \
-            -n "${NAMESPACE}" \
-            --ignore-not-found
+      #     kubectl delete job kikos-prisma-migrate \
+      #       -n "${NAMESPACE}" \
+      #       --ignore-not-found
 
-          sed "s|IMAGE_TAG|${IMAGE_TAG}|g" \
-            infra/k8s/api/prisma-migrate-job.yaml \
-            | kubectl apply -f -
+      #     sed "s|IMAGE_TAG|${IMAGE_TAG}|g" \
+      #       infra/k8s/api/prisma-migrate-job.yaml \
+      #       | kubectl apply -f -
 
-          if ! kubectl wait \
-            --for=condition=complete \
-            job/kikos-prisma-migrate \
-            -n "${NAMESPACE}" \
-            --timeout=240s; then
+      #     if ! kubectl wait \
+      #       --for=condition=complete \
+      #       job/kikos-prisma-migrate \
+      #       -n "${NAMESPACE}" \
+      #       --timeout=240s; then
 
-            echo "❌ Prisma migration failed"
+      #       echo "❌ Prisma migration failed"
 
-            kubectl logs \
-              job/kikos-prisma-migrate \
-              -n "${NAMESPACE}" \
-              --all-containers=true \
-              || true
+      #       kubectl logs \
+      #         job/kikos-prisma-migrate \
+      #         -n "${NAMESPACE}" \
+      #         --all-containers=true \
+      #         || true
 
-            exit 1
-          fi
+      #       exit 1
+      #     fi
 
-          echo "✅ Prisma migration completed"
+      #     echo "✅ Prisma migration completed"
 
 
       # ==========================================================
@@ -249,7 +249,7 @@ jobs:
         run: |
           kubectl wait \
             --for=condition=Ready \
-            certificate/kikos-crm-cert \
+            certificate/kikos-cert \
             -n "${NAMESPACE}" \
             --timeout=180s
 
